In [35]:
import numpy as np
import faiss

In [5]:
tabular_size = 105
num_classes = 2

FileNotFoundError: [Errno 2] No such file or directory: '/income/train_x.npy'

In [6]:
W = np.random.randn(tabular_size, tabular_size)

In [7]:
print(W)

[[ 0.18546488 -0.48189983 -0.52123517 ... -0.65301061  1.38794275
   0.56756945]
 [ 0.83056291  0.00879868 -0.00412867 ...  0.49846987 -0.95250369
  -0.16651595]
 [-1.46715944 -1.3647809   0.24534544 ... -0.56405817  1.31651853
   0.80690137]
 ...
 [-0.03471357  0.26123551  0.61723567 ...  0.35538823  1.82073678
  -2.54075596]
 [-0.20325699 -0.60184572  0.27205056 ...  0.48646574 -0.16076901
   1.26205178]
 [ 0.73547444 -0.52749942  1.88354267 ...  0.73740069  1.24428068
  -0.16911323]]


In [8]:
print(W.shape)

(105, 105)


In [9]:
np.linalg.inv(W)

array([[-0.2233419 ,  0.02494242,  0.22799926, ..., -0.2327377 ,
         0.14106989,  0.18694276],
       [-0.11542483,  0.07282499,  0.16994867, ..., -0.11175182,
        -0.02582537,  0.13343639],
       [-0.30845599,  0.00112827,  0.45403617, ..., -0.18324949,
         0.1506753 ,  0.2647922 ],
       ...,
       [-0.26015804, -0.1409095 ,  0.42565179, ..., -0.21980644,
         0.25235834,  0.14238178],
       [-0.14640751, -0.14130961,  0.14542857, ..., -0.09039306,
         0.21726139,  0.07742514],
       [-0.43418574, -0.01785155,  0.86778069, ..., -0.51978711,
         0.29977694,  0.24423158]])

In [18]:
x = np.random.randn(4000, tabular_size)
x

array([[-0.88889762,  0.86625243,  1.3457765 , ...,  0.00646306,
        -2.37464389, -0.42352921],
       [-1.60324745, -1.15445835,  0.0329393 , ..., -0.34245479,
         1.2501662 , -2.25588865],
       [-0.1287945 ,  0.7906565 , -0.09277832, ...,  0.29703819,
        -0.70991527, -1.22978026],
       ...,
       [ 1.07883145,  0.69041996, -0.59768834, ..., -0.48235434,
         0.01992143,  0.33116781],
       [ 0.41845821, -1.09354957, -0.05090148, ..., -1.33199999,
        -0.30016545, -0.21802165],
       [ 0.03633865,  1.37326079,  1.22055484, ..., -1.56659306,
         1.47867444,  1.44062699]])

In [28]:
Z = np.dot(x, W)

In [20]:
print(np.dot(x, W).shape)

(4000, 105)


In [21]:
min_col = int(x.shape[1] * 0.2)
max_col = int(x.shape[1] * 0.5)

In [22]:
col = np.random.choice(range(min_col, max_col), 1, replace=False)[0]

In [23]:
col

36

In [24]:
task_idx = np.random.choice([i for i in range(x.shape[1])], col, replace=False)

In [27]:
task_idx

array([ 68,  64,  67,  90,  98,  26,  33,  54,  40,  22,  92,  50,  10,
        24,  21,  95,  13,  81,  79,  45,   7,   1,  17,  61, 103,  77,
         9, 101,  41,  35,  93,  43,  51,  46,  44,  29])

In [29]:
Z

array([[ -6.14913108,   4.64020929,   8.71588795, ...,   1.70665583,
         -8.84264911,  13.57483723],
       [-13.97215075,   2.10576489,  21.23913121, ...,   4.3045787 ,
         -7.49933359,   2.16086219],
       [  0.33887199,  -7.39682196,  -1.88643583, ..., -19.33114251,
          5.78429087,   1.10043022],
       ...,
       [ -1.72721307,  -7.21799041, -12.19609245, ...,  -0.06037642,
          9.74369446,  -3.8843472 ],
       [ 15.90568784,  -8.66733958,  -1.6608105 , ...,  26.57068014,
         -4.32425014,  13.98031079],
       [ -4.18774756,   3.88374573,  -6.2682106 , ...,   2.66125303,
         -0.4157307 ,  -2.22375859]])

In [39]:
dim_k = 200

In [40]:
partition = Z[:dim_k]

In [41]:
kmeans = faiss.Kmeans(partition.shape[1], 10, niter=20, nredo=1, verbose=False,
                                          min_points_per_centroid=5 + 15, gpu=1)

In [42]:
kmeans.train(partition)

1918226.125

In [43]:
D, I = kmeans.index.search(partition, 1)

In [44]:
D

array([[12243.823 ],
       [10489.887 ],
       [11153.771 ],
       [ 6948.3604],
       [ 8240.547 ],
       [ 9714.568 ],
       [ 7898.42  ],
       [12071.432 ],
       [13108.543 ],
       [ 9613.035 ],
       [ 8872.818 ],
       [10319.797 ],
       [ 9030.317 ],
       [10064.775 ],
       [11947.091 ],
       [10777.371 ],
       [ 8890.347 ],
       [ 6854.4365],
       [10179.47  ],
       [ 5067.1777],
       [10515.399 ],
       [10411.754 ],
       [ 8468.017 ],
       [ 9109.2   ],
       [10812.623 ],
       [ 8398.862 ],
       [ 8092.4004],
       [ 5366.6045],
       [13380.738 ],
       [12734.535 ],
       [ 6720.044 ],
       [ 6924.8506],
       [ 9490.002 ],
       [11081.074 ],
       [ 8428.24  ],
       [ 6404.1855],
       [14221.699 ],
       [ 7042.5044],
       [ 9383.233 ],
       [10008.651 ],
       [ 8846.55  ],
       [10291.832 ],
       [11286.336 ],
       [ 6302.47  ],
       [ 7545.962 ],
       [ 9126.198 ],
       [11136.709 ],
       [ 8063

In [45]:
I

array([[5],
       [7],
       [5],
       [9],
       [3],
       [5],
       [9],
       [3],
       [0],
       [5],
       [9],
       [7],
       [7],
       [1],
       [5],
       [4],
       [7],
       [0],
       [4],
       [2],
       [5],
       [5],
       [8],
       [1],
       [7],
       [0],
       [7],
       [3],
       [9],
       [3],
       [0],
       [7],
       [7],
       [5],
       [7],
       [8],
       [4],
       [3],
       [9],
       [7],
       [7],
       [3],
       [0],
       [7],
       [3],
       [0],
       [9],
       [0],
       [5],
       [3],
       [2],
       [0],
       [5],
       [6],
       [0],
       [3],
       [7],
       [5],
       [5],
       [0],
       [0],
       [0],
       [5],
       [3],
       [5],
       [9],
       [1],
       [5],
       [9],
       [0],
       [7],
       [5],
       [4],
       [7],
       [7],
       [3],
       [0],
       [3],
       [0],
       [5],
       [5],
       [5],
       [5],
    